# Generated by Django 6.0.1 on 2026-02-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_client_owner_mailing_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_any_clients", "Может просматривать любых клиентов"),
                    ("can_edit_any_clients", "Может редактировать любых клиентов"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_any_mailings", "Может просматривать любые рассылки"),
                    ("can_edit_any_mailings", "Может редактировать любые рассылки"),
                    ("can_delete_any_mailings", "Может удалять любые рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_any_messages", "Может просматривать любые сообщения"),
                    ("can_edit_any_messages", "Может редактировать любые сообщения"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
