# Generated by Django 6.0.1 on 2026-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_add_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
